import type { RxItem } from './types'

/**
 * Offered once from Settings to seed the doctor's own medicine list. Defaults are starting
 * points only: every field stays editable on each prescription, and weight-based doses
 * are deliberately left blank.
 */
export const STARTER_MEDICINES: RxItem[] = [
  { name: 'Somatropin (recombinant GH) 5 mg cartridge', dose: '', frequency: 'Once daily at bedtime', route: 'Subcutaneous', duration: 'Continue', instructions: 'Rotate injection sites.' },
  { name: 'Levothyroxine 25 mcg tablet', dose: '', frequency: 'Once daily, empty stomach', route: 'Oral', duration: 'Continue', instructions: '30 minutes before breakfast.' },
  { name: 'Hydrocortisone 5 mg tablet', dose: '', frequency: 'Three times daily', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Insulin glargine 100 U/mL', dose: '', frequency: 'Once daily at bedtime', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Insulin aspart 100 U/mL', dose: '', frequency: 'Before meals', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Metformin 500 mg tablet', dose: '', frequency: 'Twice daily', route: 'Oral', duration: '3 months', instructions: 'After meals.' },
  { name: 'Leuprolide depot 3.75 mg injection', dose: '', frequency: 'Every 4 weeks', route: 'Intramuscular', duration: 'Continue', instructions: '' },
  { name: 'Cholecalciferol 60,000 IU sachet', dose: '1 sachet', frequency: 'Once weekly', route: 'Oral', duration: '8 weeks', instructions: 'After food, with milk.' },
  { name: 'Calcium carbonate 500 mg tablet', dose: '', frequency: 'Once daily', route: 'Oral', duration: '3 months', instructions: 'After food.' },

  // Added on the owner's request as a fuller master list. Names, routes and the usual interval
  // only: every dose is blank, and the doctor checks each entry before use.
  // Thyroid
  { name: 'Levothyroxine 12.5 mcg tablet', dose: '', frequency: 'Once daily, empty stomach', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Levothyroxine 50 mcg tablet', dose: '', frequency: 'Once daily, empty stomach', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Levothyroxine 75 mcg tablet', dose: '', frequency: 'Once daily, empty stomach', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Levothyroxine 100 mcg tablet', dose: '', frequency: 'Once daily, empty stomach', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Carbimazole 5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Carbimazole 10 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Propranolol 10 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Propranolol 40 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Atenolol 25 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  // Growth
  { name: 'Somatropin (recombinant GH) 12 mg cartridge', dose: '', frequency: 'Once daily at bedtime', route: 'Subcutaneous', duration: 'Continue', instructions: 'Rotate injection sites.' },
  { name: 'Somatropin (recombinant GH) 4 IU vial', dose: '', frequency: 'Once daily at bedtime', route: 'Subcutaneous', duration: 'Continue', instructions: 'Rotate injection sites.' },
  // Puberty and gonads
  { name: 'Leuprolide depot 11.25 mg injection', dose: '', frequency: 'Every 12 weeks', route: 'Intramuscular', duration: 'Continue', instructions: '' },
  { name: 'Triptorelin depot 3.75 mg injection', dose: '', frequency: 'Every 4 weeks', route: 'Intramuscular', duration: 'Continue', instructions: '' },
  { name: 'Triptorelin depot 11.25 mg injection', dose: '', frequency: 'Every 12 weeks', route: 'Intramuscular', duration: 'Continue', instructions: '' },
  { name: 'Testosterone enanthate injection', dose: '', frequency: '', route: 'Intramuscular', duration: '', instructions: '' },
  { name: 'Testosterone undecanoate 40 mg capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Testosterone gel 1%', dose: '', frequency: '', route: 'Topical', duration: '', instructions: '' },
  { name: 'hCG (human chorionic gonadotropin) injection', dose: '', frequency: '', route: 'Intramuscular', duration: '', instructions: '' },
  { name: 'Estradiol valerate 1 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Estradiol valerate 2 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Conjugated estrogens 0.625 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Estradiol transdermal patch', dose: '', frequency: '', route: 'Topical', duration: '', instructions: '' },
  { name: 'Medroxyprogesterone acetate 10 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Norethisterone 5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Micronised progesterone 100 mg capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Combined oral contraceptive pill (ethinylestradiol + levonorgestrel)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Cyproterone acetate + ethinylestradiol tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Spironolactone 25 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Letrozole 2.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Anastrozole 1 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Tamoxifen 10 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Bicalutamide 50 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  // Adrenal
  { name: 'Hydrocortisone 10 mg tablet', dose: '', frequency: '', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Hydrocortisone sodium succinate 100 mg injection', dose: '', frequency: '', route: 'Intramuscular', duration: '', instructions: 'For emergency use.' },
  { name: 'Prednisolone 5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Dexamethasone 0.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Fludrocortisone 100 mcg tablet', dose: '', frequency: 'Once daily', route: 'Oral', duration: 'Continue', instructions: '' },
  { name: 'Sodium chloride supplement (oral)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  // Diabetes and glucose
  { name: 'Insulin lispro 100 U/mL', dose: '', frequency: 'Before meals', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Insulin glulisine 100 U/mL', dose: '', frequency: 'Before meals', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Insulin degludec 100 U/mL', dose: '', frequency: 'Once daily', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Insulin detemir 100 U/mL', dose: '', frequency: '', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Regular (soluble) human insulin 40 IU/mL', dose: '', frequency: 'Before meals', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'NPH (isophane) human insulin 40 IU/mL', dose: '', frequency: '', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Premixed human insulin 30/70 40 IU/mL', dose: '', frequency: '', route: 'Subcutaneous', duration: 'Continue', instructions: '' },
  { name: 'Metformin 1000 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: 'After meals.' },
  { name: 'Metformin SR 500 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: 'After meals.' },
  { name: 'Glimepiride 1 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Liraglutide injection', dose: '', frequency: 'Once daily', route: 'Subcutaneous', duration: '', instructions: '' },
  { name: 'Glucagon 1 mg injection', dose: '', frequency: '', route: 'Intramuscular', duration: '', instructions: 'For severe hypoglycaemia.' },
  { name: 'Glucose gel or glucose tablets', dose: '', frequency: '', route: 'Oral', duration: '', instructions: 'For hypoglycaemia.' },
  { name: 'Diazoxide (oral)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Octreotide injection', dose: '', frequency: '', route: 'Subcutaneous', duration: '', instructions: '' },
  // Bone and mineral
  { name: 'Cholecalciferol drops 400 IU/mL', dose: '', frequency: 'Once daily', route: 'Oral', duration: '', instructions: '' },
  { name: 'Cholecalciferol 1000 IU tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Cholecalciferol 60,000 IU capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Calcium carbonate + vitamin D3 tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: 'After food.' },
  { name: 'Calcium syrup', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Calcium gluconate 10% injection', dose: '', frequency: '', route: 'Intravenous', duration: '', instructions: '' },
  { name: 'Calcitriol 0.25 mcg capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Alfacalcidol 0.25 mcg capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Phosphate supplement (oral)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Magnesium supplement (oral)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Zoledronic acid injection', dose: '', frequency: '', route: 'Intravenous', duration: '', instructions: '' },
  { name: 'Pamidronate injection', dose: '', frequency: '', route: 'Intravenous', duration: '', instructions: '' },
  { name: 'Alendronate 70 mg tablet', dose: '', frequency: 'Once weekly', route: 'Oral', duration: '', instructions: '' },
  { name: 'Burosumab injection', dose: '', frequency: '', route: 'Subcutaneous', duration: '', instructions: '' },
  // Water balance and pituitary
  { name: 'Desmopressin 0.1 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Desmopressin 60 mcg melt tablet', dose: '', frequency: '', route: 'Sublingual', duration: '', instructions: '' },
  { name: 'Desmopressin nasal spray 10 mcg per puff', dose: '', frequency: '', route: 'Intranasal', duration: '', instructions: '' },
  { name: 'Hydrochlorothiazide 12.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Cabergoline 0.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Bromocriptine 2.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  // Obesity, lipids and blood pressure
  { name: 'Orlistat 120 mg capsule', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Atorvastatin 10 mg tablet', dose: '', frequency: 'Once daily', route: 'Oral', duration: '', instructions: '' },
  { name: 'Enalapril 2.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Amlodipine 2.5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  // Supplements
  { name: 'Iron syrup (elemental iron)', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Folic acid 5 mg tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Zinc syrup', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Multivitamin syrup', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
  { name: 'Vitamin B12 (methylcobalamin) tablet', dose: '', frequency: '', route: 'Oral', duration: '', instructions: '' },
]
