/* AUTO-GENERATED by scripts/build-protocols.mjs from reference-data/protocols/*.json. DO NOT EDIT BY HAND.
 * Guideline-based suggestions (investigations, medicines, advice) per condition. Reference
 * content only; no patient data. Change the JSON and run `npm run build:protocols`.
 */
/* oxlint-disable */
import type { Protocol } from './protocols'

export const PROTOCOL_DATA: Protocol[] = [
 {
  "key": "congenital-hypothyroidism",
  "name": "Congenital hypothyroidism",
  "group": "Thyroid",
  "aliases": [
   "CH",
   "Hypothyroidism",
   "Congenital hypothyroidism (primary)",
   "Thyroid dysgenesis",
   "Dyshormonogenesis"
  ],
  "compiledOn": "2026-10-08",
  "review": "Draft. Compiled from the cited sources by an AI research pass; quotes were read through a summarising reader. Not yet checked by the doctor against the original documents.",
  "sources": [
   {
    "id": "S1",
    "org": "ISPAE",
    "year": 2018,
    "title": "Newborn Screening Guidelines for Congenital Hypothyroidism in India: Recommendations of the Indian Society for Pediatric and Adolescent Endocrinology (ISPAE) - Part II: Imaging, Treatment and Follow-up (Sudhanshu S, et al. Indian J Pediatr 2018;85:448-453). Only the abstract and summary were readable; the full text is behind a paywall.",
    "url": "https://link.springer.com/article/10.1007/s12098-017-2576-x"
   },
   {
    "id": "S2",
    "org": "ISPAE",
    "year": 2018,
    "title": "Newborn Screening Guidelines for Congenital Hypothyroidism in India: ISPAE Recommendations - Part I: Screening and Confirmation of Diagnosis (Desai MP, et al. Indian J Pediatr 2018;85:440-447). Abstract only.",
    "url": "https://link.springer.com/article/10.1007/s12098-017-2575-y"
   },
   {
    "id": "S3",
    "org": "IAP",
    "year": 2022,
    "title": "IAP Standard Treatment Guidelines 2022: Hypothyroidism (Ayyavoo A, Kumar R, Godbole T)",
    "url": "https://iapindia.org/pdf/Ch-012-Hypothyroidism.pdf"
   },
   {
    "id": "S4",
    "org": "ENDO-ERN / ESPE / ESE",
    "year": 2021,
    "title": "Congenital Hypothyroidism: A 2020-2021 Consensus Guidelines Update - An ENDO-European Reference Network Initiative Endorsed by ESPE and ESE (van Trotsenburg P, et al. Thyroid 2021;31:387-419). Read through the Europe PMC full-text copy of PMC8001676.",
    "url": "https://www.ebi.ac.uk/europepmc/webservices/rest/PMC8001676/fullTextXML"
   },
   {
    "id": "S5",
    "org": "Medindia (Indian drug index)",
    "year": 2023,
    "title": "Thyroxine: brands and prices in India (used only for tablet strengths)",
    "url": "https://www.medindia.net/drug-price/thyroxine.htm"
   }
  ],
  "sets": [
   {
    "name": "Confirm diagnosis",
    "when": "Venous sample after a positive newborn screen, before starting levothyroxine",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "ISPAE: primary CH and treatment if venous TSH >20 mIU/L before age 2 weeks, or >10 mIU/L after age 2 weeks.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "ISPAE: low FT4 is <1.17 ng/dL. ENDO-ERN: start treatment if TSH >20 mU/L even when FT4 is normal.",
      "sources": [
       "S1",
       "S4"
      ]
     },
     {
      "test": "Total T4",
      "category": "Thyroid",
      "unit": "µg/dL",
      "note": "Alternative to Free T4 where FT4 is not available. ISPAE: low T4 is <10 µg/dL.",
      "sources": [
       "S1"
      ]
     }
    ]
   },
   {
    "name": "Find the cause (do not delay treatment)",
    "when": "After CH is biochemically confirmed; start levothyroxine first, do not wait for scans",
    "items": [
     {
      "test": "Thyroid ultrasound",
      "category": "Imaging",
      "unit": "",
      "note": "ISPAE and IAP: ultrasound and scintigraphy after biochemical confirmation.",
      "sources": [
       "S1",
       "S3"
      ]
     },
     {
      "test": "Thyroid scintigraphy (radionuclide scan)",
      "category": "Imaging",
      "unit": "",
      "note": "IAP: scintigraphy can be done up to 7 days after starting levothyroxine (if TSH is high).",
      "sources": [
       "S1",
       "S3"
      ]
     },
     {
      "test": "Thyroglobulin",
      "category": "Thyroid",
      "unit": "",
      "note": "ENDO-ERN mentions serum thyroglobulin as useful in working out the cause. Optional.",
      "sources": [
       "S4"
      ]
     },
     {
      "test": "X-ray knee",
      "category": "Imaging",
      "unit": "",
      "note": "ENDO-ERN: knee X-ray may be performed to assess the severity of intrauterine hypothyroidism. Optional.",
      "sources": [
       "S4"
      ]
     },
     {
      "test": "Hearing assessment",
      "category": "General",
      "unit": "",
      "note": "ENDO-ERN and IAP: not just the neonatal test; repeat hearing tests before school age and as required.",
      "sources": [
       "S3",
       "S4"
      ]
     }
    ]
   },
   {
    "name": "Follow-up on levothyroxine",
    "when": "ISPAE schedule: T4/FT4 at 2 weeks; TSH and T4/FT4 at 1 month; then every 2 months till 6 months; every 3 months from 6 months to 3 years; every 3-6 months thereafter",
    "items": [
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "IAP: T4/FT4 should reach the upper half of the reference range by 2 weeks. ENDO-ERN: take blood before, or at least 4 hours after, the day's levothyroxine.",
      "sources": [
       "S1",
       "S3",
       "S4"
      ]
     },
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "IAP: TSH should reach the lower half of the reference range by 4 weeks. ENDO-ERN: keep TSH within the reference interval; extra check 4-6 weeks after any change of dose or formulation.",
      "sources": [
       "S1",
       "S3",
       "S4"
      ]
     }
    ]
   },
   {
    "name": "Re-evaluation at 3 years",
    "when": "Children with possible transient CH (for example a normally placed gland, no firm diagnosis of permanent CH): at age 3 years, after stopping levothyroxine",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "IAP: treatment can be stopped for 4 weeks at 3 years of age. ENDO-ERN: phase out over 4-6 weeks or just stop, then retest; TSH >=10 mU/L confirms primary hypothyroidism.",
      "sources": [
       "S1",
       "S3",
       "S4"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "Measured with TSH at re-evaluation.",
      "sources": [
       "S1",
       "S4"
      ]
     }
    ]
   }
  ],
  "medicines": [
   {
    "generic": "Levothyroxine",
    "rx": {
     "name": "Levothyroxine tablet",
     "dose": "",
     "frequency": "Once daily",
     "route": "Oral",
     "duration": "Continue",
     "instructions": "Give once a day at the same time every day. Crush the tablet and give it in a little water or breast milk with a spoon. Avoid giving with soy protein or high-fibre feeds."
    },
    "strengths": [
     "12.5 mcg",
     "25 mcg",
     "50 mcg",
     "75 mcg",
     "100 mcg",
     "125 mcg",
     "150 mcg"
    ],
    "verified": true,
    "doseGuide": "10-15 mcg/kg in the neonatal period (ISPAE 2018); IAP 2022 writes this as 10-15 mcg/kg/day. Later doses are adjusted to TSH and T4/FT4; no age-wise maintenance dose table could be read from an Indian guideline.",
    "max": "",
    "indication": "Primary congenital hypothyroidism, started as soon as the venous confirmatory sample is taken and the result supports CH; IAP: as soon as possible and no later than the first 2 weeks of life.",
    "monitoring": "T4/FT4 at 2 weeks; TSH and T4/FT4 at 1 month, then every 2 months till 6 months, every 3 months from 6 months to 3 years, and every 3-6 months thereafter (ISPAE). Recheck 4-6 weeks after a dose change (ENDO-ERN).",
    "prescriberNote": "",
    "note": "ISPAE abstract gives the dose per kg without '/day'; IAP STG 2022 states 'Initial thyroxine dose is 10-15 μg/kg/day'. ENDO-ERN 2020-21 differs slightly: starting dose 'up to 15 μg/kg per day', highest dose (10-15) for severe CH, about 10 for mild, and 5-10 may be considered for the mildest forms. Administration advice (same time daily, crushed tablet in water or breast milk, avoid soy and vegetable fibre, may be given with food) is from ENDO-ERN, because the ISPAE full text could not be opened. ENDO-ERN did not mention iron or calcium, so no spacing rule for those is given here. Strengths are from an Indian drug index (which also lists 37 mcg and 200 mcg), not from a formulary.",
    "quote": "Levothyroxine is commenced at 10-15 μg/kg in the neonatal period.",
    "sources": [
     "S1",
     "S2",
     "S3",
     "S4",
     "S5"
    ],
    "doseSources": [
     "S1",
     "S2",
     "S3",
     "S4"
    ]
   }
  ],
  "advice": [
   {
    "text": "Give the thyroid tablet every day at the same time. Do not stop it without asking the doctor.",
    "sources": [
     "S4"
    ]
   },
   {
    "text": "Crush the tablet and give it in a spoon with a little water or breast milk.",
    "sources": [
     "S4"
    ]
   },
   {
    "text": "Avoid soy-based feeds close to the dose.",
    "sources": [
     "S4"
    ]
   },
   {
    "text": "Come for blood tests on the dates given. On the day of the test, give the tablet after the blood sample or at least 4 hours before it.",
    "sources": [
     "S4"
    ]
   },
   {
    "text": "Hearing should be checked again before school age.",
    "sources": [
     "S3",
     "S4"
    ]
   }
  ],
  "caveats": "1) The ISPAE 2018 Part I and Part II full texts are paywalled; only the abstracts were read. The confirmatory thresholds, starting dose, follow-up schedule and 3-year re-evaluation are from those abstracts; target ranges and the follow-up intervals in IAP STG 2022 (which broadly repeats ISPAE) were read from the IAP PDF. 2) Follow-up intervals differ: ISPAE 2-monthly to 6 months then 3-monthly to 3 years; IAP STG '1-2 monthly until 6 months and 2-4 monthly from 6 to 36 months'; ENDO-ERN first review 1-2 weeks after starting, then every 2 weeks until TSH is normal, every 1-3 months to 12 months, every 2-4 months from 1 to 3 years, every 3-6 months until growth is complete. 3) ENDO-ERN says a child with a gland in situ who needs less than 3 mcg/kg per day at 6 months can be re-evaluated then. 4) ENDO-ERN recommends a careful examination of every neonate with high TSH for malformations, particularly cardiac (no routine echocardiogram is stated). 5) Central congenital hypothyroidism is not given its own entry: ENDO-ERN says to start levothyroxine only after adrenal function is shown to be intact, and to keep FT4 above the middle of the reference range. 6) ENDO-ERN advises against compounded levothyroxine solutions or suspensions. 7) Quotes were extracted through a web-fetch tool and should be spot-checked against the papers."
 },
 {
  "key": "acquired-hypothyroidism",
  "name": "Acquired hypothyroidism",
  "group": "Thyroid",
  "aliases": [
   "Hypothyroidism",
   "Hashimoto thyroiditis",
   "Autoimmune thyroiditis",
   "Subclinical hypothyroidism",
   "SCH",
   "Goitre"
  ],
  "compiledOn": "2026-10-08",
  "review": "Draft. Compiled from the cited sources by an AI research pass; quotes were read through a summarising reader. Not yet checked by the doctor against the original documents.",
  "sources": [
   {
    "id": "S1",
    "org": "IAP",
    "year": 2022,
    "title": "IAP Standard Treatment Guidelines 2022: Hypothyroidism (Ayyavoo A, Kumar R, Godbole T)",
    "url": "https://iapindia.org/pdf/Ch-012-Hypothyroidism.pdf"
   },
   {
    "id": "S2",
    "org": "ETA",
    "year": 2014,
    "title": "2014 European Thyroid Association Guidelines for the Management of Subclinical Hypothyroidism in Pregnancy and in Children (Lazarus J, et al. Eur Thyroid J 2014;3:76-94)",
    "url": "https://research.dial.uclouvain.be/bitstreams/36caacb8-bfd3-4305-8d22-b7c084f840e0/download"
   },
   {
    "id": "S3",
    "org": "ATA",
    "year": 2014,
    "title": "Guidelines for the Treatment of Hypothyroidism, American Thyroid Association Task Force on Thyroid Hormone Replacement (Jonklaas J, et al. Thyroid 2014). Only the general (adult) sections on how to take levothyroxine could be read; the section on infants and children could not.",
    "url": "https://www.societaitalianadiendocrinologia.it/wp-content/uploads/2024/09/ipotiroidismolg.pdf"
   },
   {
    "id": "S4",
    "org": "Indian Pediatrics (review, not a guideline)",
    "year": 2014,
    "title": "Subclinical Hypothyroidism in Children (Shriraam M, Sridhar M. Indian Pediatr 2014;51:889-895)",
    "url": "https://indianpediatrics.net/nov2014/nov-889-895.htm"
   },
   {
    "id": "S5",
    "org": "Medindia (Indian drug index)",
    "year": 2023,
    "title": "Thyroxine: brands and prices in India (used only for tablet strengths)",
    "url": "https://www.medindia.net/drug-price/thyroxine.htm"
   }
  ],
  "sets": [
   {
    "name": "At diagnosis",
    "when": "Before starting levothyroxine",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "IAP: essential.",
      "sources": [
       "S1"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "IAP: essential (total T4 or free T4).",
      "sources": [
       "S1"
      ]
     },
     {
      "test": "Total T4",
      "category": "Thyroid",
      "unit": "µg/dL",
      "note": "Alternative to Free T4.",
      "sources": [
       "S1"
      ]
     },
     {
      "test": "Anti-TPO antibodies",
      "category": "Thyroid",
      "unit": "",
      "note": "IAP: optional. ETA 2014 uses TPO antibody status to set how often to recheck subclinical hypothyroidism.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Anti-thyroglobulin antibodies",
      "category": "Thyroid",
      "unit": "",
      "note": "IAP: optional.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Thyroid ultrasound",
      "category": "Imaging",
      "unit": "",
      "note": "IAP: ultrasound if necessary, for primary hypothyroidism.",
      "sources": [
       "S1"
      ]
     },
     {
      "test": "MRI pituitary with contrast",
      "category": "Imaging",
      "unit": "",
      "note": "Only for central hypothyroidism (low FT4 without a raised TSH). IAP words this as 'MRI brain'.",
      "sources": [
       "S1"
      ]
     }
    ]
   },
   {
    "name": "Follow-up on levothyroxine",
    "when": "4-6 weeks after starting or changing the dose; the IAP guideline gives no routine interval once the dose is stable",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "IAP: adjust the dose to keep TSH and T4/FT4 in range. The 4-6 week recheck after a dose change is from the ATA 2014 guideline (adult section).",
      "sources": [
       "S1",
       "S3"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "With TSH.",
      "sources": [
       "S1"
      ]
     }
    ]
   },
   {
    "name": "Subclinical hypothyroidism: watch without treatment",
    "when": "Raised TSH with normal T4/FT4, child over 3 years, not on levothyroxine. Antibodies negative: recheck at 1 year, then less often if no worsening. Antibodies positive: every 6-12 months; more often if the first TSH was above 10 mU/L.",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "ETA 2014 recommendations 26 and 28. Confirm a raised TSH on a repeat sample before labelling (Indian Pediatrics review).",
      "sources": [
       "S2",
       "S4"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "Must be normal for the label 'subclinical'.",
      "sources": [
       "S2"
      ]
     },
     {
      "test": "Anti-TPO antibodies",
      "category": "Thyroid",
      "unit": "",
      "note": "ETA 2014: monitor TSH and TPO antibody in antibody-negative children; TSH with or without TPO antibody in antibody-positive children.",
      "sources": [
       "S2"
      ]
     }
    ]
   }
  ],
  "medicines": [
   {
    "generic": "Levothyroxine",
    "rx": {
     "name": "Levothyroxine tablet",
     "dose": "",
     "frequency": "Once daily",
     "route": "Oral",
     "duration": "Continue",
     "instructions": "Take once a day, consistently either 60 minutes before breakfast or at bedtime. Keep it apart from iron, calcium and other medicines that interfere with absorption."
    },
    "strengths": [
     "12.5 mcg",
     "25 mcg",
     "50 mcg",
     "75 mcg",
     "100 mcg",
     "125 mcg",
     "150 mcg"
    ],
    "verified": true,
    "doseGuide": "By weight: age 1-3 years 4-6 mcg/kg; age 3-10 years 3-5 mcg/kg; age 10-16 years 2-4 mcg/kg. Or by body surface area: 100 mcg/m². Long-standing, severe, untreated hypothyroidism: start at a lower dose and step up over several weeks. (IAP STG 2022)",
    "max": "",
    "indication": "Overt acquired primary hypothyroidism (for example Hashimoto thyroiditis). In subclinical hypothyroidism (raised TSH, normal FT4) the decision to treat is individual: ETA 2014 finds insufficient evidence to treat most children with TSH below 10 mU/L.",
    "monitoring": "TSH and T4/FT4; adjust the dose to keep both in range (IAP). Recheck TSH 4-6 weeks after any dose change (ATA 2014).",
    "prescriberNote": "",
    "note": "The IAP table gives doses per kg body weight without writing '/day'; they are daily doses. It gives no band under 1 year (use the congenital hypothyroidism entry) or over 16 years. The quote joins four separate lines of the IAP table. The timing advice (60 minutes before breakfast or at bedtime; separate from interfering medicines) is from the ATA 2014 guideline's general recommendations 3a and 3b, which were written for adults; that guideline calls a 4-hour separation 'traditional, but untested'. The IAP guideline says nothing on how to take the tablet. Strengths are from an Indian drug index.",
    "quote": "Age 1-3 years: 4-6 µg/kg body weight; Age 3-10 years: 3-5 µg/kg; Age 10-16 years: 2-4 µg/kg; 100 µg/m2 BSA (OR)",
    "sources": [
     "S1",
     "S2",
     "S3",
     "S5"
    ],
    "doseSources": [
     "S1",
     "S2",
     "S3"
    ]
   }
  ],
  "advice": [
   {
    "text": "Take the thyroid tablet every day at the same time, either 60 minutes before breakfast or at bedtime.",
    "sources": [
     "S3"
    ]
   },
   {
    "text": "Keep iron and calcium medicines well apart from the thyroid tablet.",
    "sources": [
     "S3"
    ]
   },
   {
    "text": "Do not stop the tablet on your own; the treatment is usually long term.",
    "sources": [
     "S1"
    ]
   },
   {
    "text": "A blood test is needed 4-6 weeks after any change of dose.",
    "sources": [
     "S3"
    ]
   }
  ],
  "caveats": "1) No Indian guideline was found that gives a follow-up interval for a child on a stable levothyroxine dose, a TSH target, or a treatment threshold for subclinical hypothyroidism; the IAP STG 2022 is silent on all three. 2) Subclinical hypothyroidism guidance is from ETA 2014: under 3 years with TSH not normalised after 1 month of age, treat until 3 years then trial off; over 3 years, monitor as set out above; treatment decision after discussion with parents; 'reasonable to treat' after thyroid irradiation; regular thyroid monitoring in trisomy 21. ETA 2014 gives no levothyroxine dose for children. 3) ETA 2014 notes that a TSH of 5-7 mU/L in an obese child is likely the consequence, not the cause, of the obesity. 4) The Indian Pediatrics 2014 article is a review, not a guideline; it is used only for 'repeat the TSH before labelling' and agrees that treatment is not justified when TSH is below 10 mIU/L without other risk factors. 5) The paediatric section of the ATA 2014 hypothyroidism guideline and the BNF for Children could not be opened, so their age-wise doses are not included. 6) Screening for coeliac disease or type 1 diabetes in autoimmune thyroiditis is not included: no guideline statement was found for it from the thyroid side. 7) Quotes were extracted through a web-fetch tool and should be spot-checked."
 },
 {
  "key": "graves-disease-hyperthyroidism",
  "name": "Graves disease / hyperthyroidism",
  "group": "Thyroid",
  "aliases": [
   "Hyperthyroidism",
   "Graves disease",
   "Thyrotoxicosis",
   "GD"
  ],
  "compiledOn": "2026-10-08",
  "review": "Draft. Compiled from the cited sources by an AI research pass; quotes were read through a summarising reader. Not yet checked by the doctor against the original documents.",
  "sources": [
   {
    "id": "S1",
    "org": "IAP",
    "year": 2022,
    "title": "IAP Standard Treatment Guidelines 2022: Hyperthyroidism (Riaz I, Bhakhri BK, Mehta S). Read only through a Medical Dialogues summary dated 16 April 2023; the IAP PDF itself could not be opened.",
    "url": "https://comments.medicaldialogues.in/pediatrics-neonatology/guidelines/hyperthyroidism-in-children-iap-guidelines-109442"
   },
   {
    "id": "S2",
    "org": "ETA",
    "year": 2022,
    "title": "2022 European Thyroid Association Guideline for the management of pediatric Graves' disease (Mooij CF, et al. Eur Thyroid J 2022;11(1):e210073). Read from the copy hosted by BSPED.",
    "url": "https://www.bsped.org.uk/media/ud1d2gaz/etj-etj-21-0073-graves-disease-guildelines-2022.pdf"
   },
   {
    "id": "S3",
    "org": "Medindia (Indian drug index)",
    "year": 2023,
    "title": "Carbimazole, propranolol and atenolol: brands and prices in India (used only for strengths)",
    "url": "https://www.medindia.net/drug-price/carbimazole.htm"
   },
   {
    "id": "S4",
    "org": "Scottish Paediatric Endocrine Group (NHS Scotland)",
    "year": 2021,
    "title": "Medical management of children with thyrotoxicosis: treatment (regional guideline; used only as a cross-check)",
    "url": "https://www.rightdecisions.scot.nhs.uk/speg-scottish-paediatric-endocrine-group/medical-management-of-children-with-thyrotoxicosis/treatment/"
   }
  ],
  "sets": [
   {
    "name": "At diagnosis",
    "when": "Before starting an antithyroid drug",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "Suppressed in hyperthyroidism.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Free T3",
      "category": "Thyroid",
      "unit": "",
      "note": "",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "TSH receptor antibodies (TRAb)",
      "category": "Thyroid",
      "unit": "",
      "note": "ETA: recommended for all paediatric patients with hyperthyroidism; if negative but Graves disease is likely, repeat after a few weeks.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Anti-TPO antibodies",
      "category": "Thyroid",
      "unit": "",
      "note": "ETA: measure with TRAb.",
      "sources": [
       "S2"
      ]
     },
     {
      "test": "Thyroid ultrasound",
      "category": "Imaging",
      "unit": "",
      "note": "ETA: ultrasound with Doppler is preferred to scintigraphy, to avoid radiation.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Thyroid scintigraphy (radionuclide scan)",
      "category": "Imaging",
      "unit": "",
      "note": "Not routine. ETA: better for identifying a 'hot' autonomous nodule. IAP: shows increased uptake in Graves disease.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Complete blood count",
      "category": "General",
      "unit": "",
      "note": "Baseline, with neutrophil count, before the first dose (IAP and ETA).",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Liver function tests",
      "category": "General",
      "unit": "",
      "note": "Baseline, before the first dose (IAP and ETA).",
      "sources": [
       "S1",
       "S2"
      ]
     }
    ]
   },
   {
    "name": "Follow-up on antithyroid drug",
    "when": "IAP: free T4 and T3 every 4-6 weeks while titrating, then 3-monthly once euthyroid. ETA: every 4 weeks for the first 3 months, then 2-monthly and then 3-monthly depending on the course.",
    "items": [
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "ETA: be guided by thyroid hormone levels, not TSH, in the first 4-6 months.",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "Free T3",
      "category": "Thyroid",
      "unit": "",
      "note": "",
      "sources": [
       "S1",
       "S2"
      ]
     },
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "May stay suppressed for several months after FT4/FT3 are normal (ETA).",
      "sources": [
       "S2"
      ]
     }
    ]
   },
   {
    "name": "Fever or sore throat on antithyroid drug",
    "when": "Same day: stop the drug and test",
    "items": [
     {
      "test": "Complete blood count",
      "category": "General",
      "unit": "",
      "note": "With neutrophil count. ETA: stop the drug if neutrophils are below 0.5 x10^9/L; 0.5-1.5 can be watched with once or twice weekly counts.",
      "sources": [
       "S2"
      ]
     }
    ]
   },
   {
    "name": "Signs of liver dysfunction on antithyroid drug (for example jaundice)",
    "when": "When signs of liver dysfunction appear",
    "items": [
     {
      "test": "Liver function tests",
      "category": "General",
      "unit": "",
      "note": "ETA: transaminases more than three times the upper limit of normal warrant stopping the drug.",
      "sources": [
       "S2"
      ]
     }
    ]
   },
   {
    "name": "Before stopping antithyroid drug",
    "when": "After at least 3 years of treatment (ETA)",
    "items": [
     {
      "test": "TSH receptor antibodies (TRAb)",
      "category": "Thyroid",
      "unit": "",
      "note": "ETA: stop only when TRAb has been low for several months; if raised, remission is unlikely and the drug should not be stopped.",
      "sources": [
       "S2"
      ]
     }
    ]
   },
   {
    "name": "After stopping antithyroid drug",
    "when": "Every 3-4 months in the first year, every 6 months in the second year, then yearly (ETA)",
    "items": [
     {
      "test": "TSH",
      "category": "Thyroid",
      "unit": "mIU/L",
      "note": "Watching for relapse.",
      "sources": [
       "S2"
      ]
     },
     {
      "test": "Free T4",
      "category": "Thyroid",
      "unit": "ng/dL",
      "note": "",
      "sources": [
       "S2"
      ]
     },
     {
      "test": "Free T3",
      "category": "Thyroid",
      "unit": "",
      "note": "",
      "sources": [
       "S2"
      ]
     }
    ]
   }
  ],
  "medicines": [
   {
    "generic": "Carbimazole",
    "rx": {
     "name": "Carbimazole tablet",
     "dose": "",
     "frequency": "Once daily",
     "route": "Oral",
     "duration": "Continue",
     "instructions": "Take once a day. STOP the tablet and get a blood count the same day if there is fever or sore throat. Report jaundice or a rash."
    },
    "strengths": [
     "5 mg",
     "10 mg",
     "20 mg"
    ],
    "verified": true,
    "doseGuide": "IAP STG 2022: 0.5-0.7 mg/kg/day. ETA 2022: initial 0.25-0.75 mg/kg daily; dose titration preferred, starting 0.25-0.5 mg/kg/day (up to 0.75 mg/kg/day in severe cases), then reduce by 25-50% as thyroid function normalises.",
    "max": "No mg ceiling is stated by IAP or ETA. ETA: if still thyrotoxic at about 1.3 mg/kg/day, discuss surgery or radioiodine.",
    "indication": "First-line antithyroid drug for Graves disease in children (carbimazole or methimazole; not propylthiouracil).",
    "monitoring": "Blood count with neutrophils and liver function before starting. Free T4 and T3 every 4-6 weeks while titrating, then 3-monthly (IAP). Blood count at once for fever or sore throat; liver tests if signs of liver dysfunction (ETA).",
    "prescriberNote": "",
    "note": "The quote is from ETA 2022, which was read directly. The IAP figure (0.5-0.7 mg/kg/day) is from a Medical Dialogues summary of the IAP guideline; it sits inside the ETA range. Neither says to divide the dose; ETA says once daily is sufficient. Block-and-replace (ETA: carbimazole 0.5-0.75 mg/kg/day with levothyroxine added in a low, age- and weight-appropriate dose once FT4/FT3 normalise) is described by ETA as having more adverse events in one trial; dose titration is preferred. A Scottish regional guideline caps the initial dose at 40 mg per day; this is not in IAP or ETA. Strengths are from an Indian drug index.",
    "quote": "The initial antithyroid drug (ATD) dose is between 0.15 and 0.5 mg/kg of MMI or between 0.25 and 0.75 mg/kg of CBZ daily.",
    "sources": [
     "S1",
     "S2",
     "S3"
    ],
    "doseSources": [
     "S1",
     "S2"
    ]
   },
   {
    "generic": "Methimazole (thiamazole)",
    "rx": {
     "name": "Methimazole (thiamazole) tablet",
     "dose": "",
     "frequency": "Once daily",
     "route": "Oral",
     "duration": "Continue",
     "instructions": "Take once a day. STOP the tablet and get a blood count the same day if there is fever or sore throat. Report jaundice or a rash."
    },
    "strengths": [],
    "verified": true,
    "doseGuide": "IAP STG 2022: 0.1-1 mg/kg/day. ETA 2022: initial 0.15-0.5 mg/kg daily; dose titration preferred, starting 0.15-0.3 mg/kg/day (up to 0.5 mg/kg/day in severe cases), then reduce by 25-50% as thyroid function normalises.",
    "max": "No mg ceiling is stated by IAP or ETA. ETA: if still thyrotoxic at about 1.0 mg/kg/day, discuss surgery or radioiodine.",
    "indication": "Alternative to carbimazole as first-line antithyroid drug for Graves disease in children.",
    "monitoring": "Same as carbimazole.",
    "prescriberNote": "",
    "note": "The quote is the IAP STG 2022 wording as reproduced in a Medical Dialogues summary; the IAP PDF itself could not be opened. The IAP range (0.1-1 mg/kg/day) is wider than ETA 2022 (0.15-0.5 mg/kg/day initial; about 1.0 mg/kg/day is the point at which ETA says to discuss definitive treatment). No Indian drug-index listing for methimazole could be opened, so strengths are left blank. Carbimazole is converted to methimazole in the body; the two are not dose-for-dose equal (ETA gives separate ranges).",
    "quote": "Methimazole (MMI) 0.1–1 mg/kg/d or carbimazole 0.5–0.7 mg/kg/d is preferred over propylthiouracil (PTU) among children.",
    "sources": [
     "S1",
     "S2"
    ],
    "doseSources": [
     "S1",
     "S2"
    ]
   },
   {
    "generic": "Propranolol",
    "rx": {
     "name": "Propranolol tablet",
     "dose": "",
     "frequency": "",
     "route": "Oral",
     "duration": "",
     "instructions": "For palpitations and tremor while the main medicine starts to work."
    },
    "strengths": [
     "10 mg",
     "20 mg",
     "40 mg",
     "80 mg"
    ],
    "verified": false,
    "doseGuide": "",
    "max": "",
    "indication": "Symptom control (tachycardia, tremor) in marked thyroid hormone excess, added to the antithyroid drug.",
    "monitoring": "Heart rate and symptoms.",
    "prescriberNote": "Do not use in a child with asthma.",
    "note": "Marked not verified because the dose comes only from a Medical Dialogues summary of the IAP guideline (the IAP PDF could not be opened) and the number of doses per day is not given. ETA 2022 gives no figure: 'A beta-blocker (e.g. propranolol or atenolol) should be administered in an age- or weight-appropriate dose', avoided in asthma. As a cross-check, a Scottish regional guideline writes '250–750 µg/kg/dose three times per day'. BNF for Children could not be opened. Strengths are from an Indian drug index, which also lists sustained-release forms.",
    "quote": "Addition of beta-blockers like propranolol, 1–2 mg/kg/d helps in early control of symptoms",
    "sources": [
     "S1",
     "S2",
     "S3",
     "S4"
    ],
    "doseSources": [
     "S1",
     "S2",
     "S4"
    ]
   },
   {
    "generic": "Atenolol",
    "rx": {
     "name": "Atenolol tablet",
     "dose": "",
     "frequency": "",
     "route": "Oral",
     "duration": "",
     "instructions": ""
    },
    "strengths": [
     "12.5 mg",
     "25 mg",
     "50 mg",
     "100 mg"
    ],
    "verified": false,
    "doseGuide": "",
    "max": "",
    "indication": "Alternative beta-blocker for symptom control, named by ETA 2022.",
    "monitoring": "Heart rate and symptoms.",
    "prescriberNote": "",
    "note": "The guideline names atenolol but gives no dose, and no other source with a paediatric thyrotoxicosis dose could be opened. Dose left blank for the doctor to fill in. Strengths are from an Indian drug index (which also lists 5 mg).",
    "quote": "A beta-blocker (e.g. propranolol or atenolol) should be administered in an age- or weight-appropriate dose.",
    "sources": [
     "S2",
     "S3"
    ],
    "doseSources": [
     "S2"
    ]
   }
  ],
  "advice": [
   {
    "text": "If your child has fever or a sore throat: STOP the thyroid tablet and get a blood count done the same day.",
    "sources": [
     "S2"
    ]
   },
   {
    "text": "Report jaundice (yellow eyes), a skin rash, blisters in the mouth or joint pains.",
    "sources": [
     "S1",
     "S2"
    ]
   },
   {
    "text": "Treatment usually continues for several years. Do not stop the tablets without advice, even when your child feels well.",
    "sources": [
     "S2"
    ]
   },
   {
    "text": "Blood tests are needed every 4-6 weeks at first, then every 3 months.",
    "sources": [
     "S1"
    ]
   }
  ],
  "caveats": "1) PROPYLTHIOURACIL: ETA 2022 states 'Propylthiouracil (PTU) should not be used because of the risk of hepatic failure'; IAP prefers methimazole or carbimazole over PTU in children. PTU is deliberately not offered as a starter medicine. 2) Blood counts and liver tests: both IAP and ETA ask for them at baseline. ETA does not set a routine schedule during treatment; it asks for a neutrophil count with fever or sore throat and liver tests with signs of liver dysfunction. Stop the drug for neutrophils below 0.5 x10^9/L or transaminases above three times the upper limit of normal. 3) Duration differs: IAP 1-2 years before considering definitive therapy; ETA at least 3 years, and only stop when TRAb has been low for several months. 4) The IAP Standard Treatment Guideline on hyperthyroidism was read only through a Medical Dialogues summary; every IAP figure here should be checked against the IAP PDF. 5) The paediatric section of the ATA 2016 hyperthyroidism guideline could not be opened in any copy (every copy was cut off before that section), so its age-banded methimazole doses are not included. 6) Definitive treatment (ETA): radioiodine avoided under 5 years and used at 5-10 years only when surgery is not a realistic option; total thyroidectomy by a high-volume thyroid surgeon. IAP: surgery or radioiodine preferred for a toxic nodule or multinodular goitre. 7) Neonatal thyrotoxicosis is not covered by either source read. 8) Eye signs: ETA advises referral to an orbital specialist. 9) Quotes were extracted through a web-fetch tool and should be spot-checked."
 }
]
